export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_SELECTED_EMPLOYEE = "FETCH_SELECTED_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";